# Generated by Django 5.1.7 on 2025-03-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
